# Multi-stage Dockerfile for Next.js 15 app

# -------------------------
# Stage 1: builder
# -------------------------
FROM  git.makecodes.dev/docker/node22-alpine:latest AS builder
WORKDIR /app

# Dependências de sistema mínimas (adapte se precisar de compilação nativa)
RUN apk add --no-cache libc6-compat curl

# Habilita pnpm via corepack
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate

# Copy package files and install dependencies (cache layer)
COPY package.json pnpm-lock.yaml* ./
# Prisma generate runs on postinstall, so we need the schema
COPY prisma ./prisma
RUN pnpm install --frozen-lockfile

# Allow configuring backend URL during build (embedded in client bundle)
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

# Allow configuring Statsig key during build (embedded in client bundle)
ARG NEXT_PUBLIC_STATSIG_CLIENT_KEY
ENV NEXT_PUBLIC_STATSIG_CLIENT_KEY=${NEXT_PUBLIC_STATSIG_CLIENT_KEY}

# Application Version Argument
ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

# Copy remaining code and build
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm run build


# -------------------------
# Stage 2: runner-prod
# Production: only production dependencies and build artifacts
# -------------------------
# Security: Use Distroless to remove shell, package managers, and other attack vectors
FROM gcr.io/distroless/nodejs22-debian12 AS runner-prod
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Keep variable at runtime for consistency
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

# Copy artifacts generated by builder (standalone)
# - .next/standalone contains Node server and necessary node_modules
# - .next/static contains Next.js static assets
# - public contains app assets
# Security: Ensure files are owned by the nonroot user
COPY --from=builder --chown=nonroot:nonroot /app/.next/standalone ./
COPY --from=builder --chown=nonroot:nonroot /app/.next/static ./.next/static


# Security: Use nonroot user provided by Distroless (uid 65532)
USER nonroot

EXPOSE 3000

# Start standalone server
CMD ["server.js"]


# -------------------------
# Stage 3: runner-dev
# Development: includes sources and dev dependencies; useful for dev container
# -------------------------
FROM git.makecodes.dev/docker/node22-alpine AS runner-dev
WORKDIR /app

# Install curl for development and debugging
RUN apk add --no-cache curl openssl

ENV NODE_ENV=development

# Install all dependencies (including dev) to run `pnpm run dev`
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
COPY package.json pnpm-lock.yaml* ./
COPY prisma ./prisma
RUN pnpm install --frozen-lockfile

# Copy all source code to allow hot-reload when using volume mount
COPY . .

EXPOSE 3000

# Development command (turbopack)
# When mounting a named volume at /app/node_modules, it starts empty and
# overrides node_modules created during image build. Ensure dependencies
# exist by installing if necessary, then start dev server.
CMD ["sh", "-lc", "echo 'Installing deps (pnpm install) on startup...'; pnpm install; npx prisma generate; pnpm run dev"]




# -------------------------
# Stage 4: final (default)
# Production as default final stage (does not require --target)
# -------------------------
FROM runner-prod
